SELECT * FROM PAYMENT WHERE TYPE_ID = (SELECT ID FROM paymenttype WHERE NAME = 'MONTHLY' );
SELECT * FROM MARK WHERE SUBJECT_ID = (SELECT ID FROM SUBJECT WHERE NAME = 'Art');
SELECT * FROM STUDENT s WHERE EXISTS (SELECT ID FROM PAYMENT WHERE STUDENT_ID = s.ID AND TYPE_ID = (SELECT ID FROM paymenttype WHERE NAME = 'WEEKLY'));
SELECT * FROM STUDENT s WHERE EXISTS (SELECT ID FROM MARK WHERE STUDENT_ID = s.ID AND SUBJECT_ID = (SELECT ID FROM SUBJECT WHERE NAME = 'Math'));