SELECT MAX(BIRTHDAY) FROM STUDENT;
SELECT MIN(PAYMENT_DATE) FROM PAYMENT;
SELECT AVG(MARK) FROM MARK WHERE SUBJECT_ID = (SELECT ID FROM SUBJECT WHERE name = 'Math');
SELECT MIN(AMOUNT) FROM PAYMENT WHERE TYPE_ID = (SELECT ID FROM paymenttype WHERE name = 'WEEKLY');
