SELECT * FROM STUDENT s WHERE 8 < (SELECT AVG(MARK) FROM MARK m WHERE s.ID = m.STUDENT_ID);
SELECT ID, NAME FROM STUDENT s WHERE 7 < (SELECT MIN(MARK) FROM MARK m WHERE s.ID = m.STUDENT_ID);
SELECT ID, NAME FROM STUDENT s WHERE 2 < (SELECT COUNT(p.ID) FROM PAYMENT p WHERE s.ID = p.STUDENT_ID AND EXTRACT('YYYY' FROM p.PAYMENT_DATE) = 2019);
