SELECT s.* FROM SUBJECT s, (SELECT AVG(MARK) a FROM MARK) ma WHERE ma.a < (SELECT AVG(MARK) FROM MARK m WHERE s.ID = m.SUBJECT_ID);
SELECT s.* FROM STUDENT s, (SELECT AVG(s) a FROM (SELECT sum(AMOUNT) s FROM PAYMENT GROUP BY STUDENT_ID)) pa WHERE pa.a > (SELECT AVG(AMOUNT) FROM PAYMENT p WHERE s.ID = p.STUDENT_ID);
