SELECT s.* FROM SUBJECT s, (SELECT AVG(MARK) a FROM MARK) ma WHERE ma.a < (SELECT AVG(MARK) FROM MARK m WHERE s.ID = m.SUBJECT_ID);
SELECT s.* FROM STUDENT s, (SELECT AVG(AMOUNT) a FROM PAYMENT) pa WHERE pa.a > (SELECT AVG(AMOUNT) FROM PAYMENT p WHERE s.ID = p.STUDENT_ID);
